### ISSUE TITLE
Process Priority Class is not shown

### ISSUE THREAD

**Issue by Alois-xx** [zodiacon/CPUStress#2]
There is no checkbox showing at which priority the process is currently running:

![grafik](https://github.com/zodiacon/CPUStress/assets/408821/27ee9396-85be-4e7d-9d78-63b499017716)

The old CPUStres tool did show also the current process priority in the toolbar. That is useful if one wants to demonstrate
scheduling issues on hybrid CPUs based on the process priority.

**Comment by zodiacon** [comment]
You're right, thanks for reporting!
Fixed.
